### ISSUE TITLE
Digram not rendering correctly

### ISSUE THREAD

**Issue by igauravsehrawat** [DrummerHead/react-flow-diagram#3]
Hi,
Great library.
I am running into an issue where the graph on initial render just render half-ish.

![screen shot 2018-07-20 at 14 14 20](https://user-images.githubusercontent.com/3696327/42996814-549af7ca-8c32-11e8-94f3-ae2b8d0b7ff7.png)

I haven't modified anything, just used your's `react-flow-diagram-example` repo `CustomDiagram` and wrapped it inside a div in my react app.

Stuck on this for long. Any help would be appreciated.
Any hint on debugging?

Thanks

Edit: My React app is ejected.

**Comment by igauravsehrawat** [comment]
~This issue only arise in development version and not the build version. Bit weird.~
~This issue might help someone save time.~

Issue still exists, sorry for confusion.

**Comment by ericzon** [comment]
I am experiencing the same issue but I've just installed your dependency, is not dev version. I'm using the example taken from CustomDiagram.

I've just uploaded an example video: https://youtu.be/-XPewKzoukA

P.S: my app is not ejected

**Comment by elmbrent** [comment]
So how do i convert out of development mode?

**Comment by alexandrudanpop** [comment]
would like to see this working! I like this library

**Comment by digitamo** [comment]
Hi, I know this is ages late :hourglass: 

The canvas dimensions are calculated from the bounding element by default the min-height is `10em` as you can see [here](https://github.com/DrummerHead/react-flow-diagram/blob/master/src/canvas/component.js#L30).
To solve this you can wrap the diagram component into an element with the height you desire like the included [demo](https://github.com/DrummerHead/react-flow-diagram/blob/master/demo/src/index.js#L27)

```javascript
const Main = styled.main`
  max-width: 62em;
  padding: 1em;
  margin: 0 auto;
  font-family: sans-serif;
  display: flex;
  flex-flow: column nowrap;
  min-height: 150vh;
`;

class Demo extends React.PureComponent<{}> {
  
  ...

  render() {
    return (
      <Main>
        <h1>react-flow-diagram Demo</h1>
        <Diagram customEntities={customEntities} />
      </Main>
    );
  }
```

**Comment by igauravsehrawat** [comment]
@digitamo Better late than never.

Great find, thanks.
